audio_data:
  type: "log"
  sampling_rate: 16000
  window_size: 0.02
  window_stride: 0.01
  window: 'hamming'

model:
  type: transducer
  cnn_encoder:
    local_cnn_encoder: 
        kernel_size: 5
        stride: 1
        feature_dim: 192
        dim_out: 160
    global_cnn_encoder:
        n_layers: 3
        kernel_size_pw: 1
        kernel_size_dw: 3
        stride: 1
        input_dim: 160   
        hidden_dim: 320
        n_dropout: 0.1
    dim_out: 192
  enc:
      type: lstm
      hidden_size: 320  
      output_size: 320
      n_layers: 4
      bidirectional: False
  dec:
      type: lstm
      embedding_size: 512
      hidden_size: 512
      output_size: 320
      n_layers: 2
  joint:
      input_size: 640
      inner_size: 512

  vocab_size: 4866
  feature_dim: 192
  dropout: 0.3
  name : 'conv-rnnt'
  share_weight: False
  

training:
  epochs: 100
  batch_size: 2
  save_path: "workspace/conv-rnnt/saves"
  voice_path: "workspace/dataset/voices"
  train_path : "workspace/dataset/train_w2i.json"
  dev_path : "workspace/dataset/test_w2i.json"
  test_path : "workspace/dataset/test_w2i.json"
  vocab_path : "workspace/dataset/vocab_w2i.json"
  reload: False


optim:
  # type: sgd
  # lr: 0.0005
  # momentum: 0.9
  # weight_decay: 0
  # begin_to_adjust_lr: 60
  # nesterov: None
  # decay_rate: 0.5

  type: adam
  lr: 0.001
  weight_decay: 0
  decay_rate: 0.5



rnnt_loss:
  blank: 4
  reduction: "mean" 